# Generated by Django 4.0.5 on 2022-06-10 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autentication', '0003_alter_orden_id_user_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='item_sale',
            name='id_orden',
        ),
        migrations.RemoveField(
            model_name='item_sale',
            name='id_prodcuto',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='id_user',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.DeleteModel(
            name='Item_sale',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='Prodcuts',
        ),
    ]
