# Generated by Django 4.0.5 on 2022-06-10 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Prodcuts',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=10)),
                ('Sub_total', models.IntegerField()),
                ('Iva', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item_sale',
            fields=[
                ('id_item_sale', models.AutoField(primary_key=True, serialize=False)),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizza.orden')),
                ('id_prodcuto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizza.prodcuts')),
            ],
        ),
    ]
