# Generated by Django 4.0.5 on 2022-06-10 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id_state', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='orden',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizza.state'),
        ),
    ]
