# Generated by Django 4.0.5 on 2022-06-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0002_state_alter_orden_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodcuts',
            new_name='Products',
        ),
        migrations.RenameField(
            model_name='item_sale',
            old_name='id_prodcuto',
            new_name='id_product',
        ),
    ]
