# Generated by Django 4.0.5 on 2022-06-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0003_rename_prodcuts_products_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
