# Generated by Django 4.0.5 on 2022-06-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0004_rename_category_categorie_rename_products_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('desciption', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.RemoveField(
            model_name='item_sale',
            name='id_orden',
        ),
        migrations.RemoveField(
            model_name='item_sale',
            name='id_product',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='state',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.DeleteModel(
            name='Item_sale',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
