# Generated by Django 4.0.5 on 2022-06-13 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pizza', '0005_category_delete_categorie_remove_item_sale_id_orden_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('orden_date', models.DateTimeField(auto_now=True)),
                ('Sub_total', models.IntegerField()),
                ('Iva', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizza.state')),
            ],
        ),
    ]
