# Generated by Django 4.0.5 on 2022-06-13 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0006_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizza.category')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizza.type')),
            ],
        ),
        migrations.CreateModel(
            name='Item_sale',
            fields=[
                ('id_item_sale', models.AutoField(primary_key=True, serialize=False)),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizza.orden')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizza.product')),
            ],
        ),
    ]
