# Generated by Django 4.0.5 on 2022-06-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0008_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
