# Generated by Django 4.0.5 on 2022-06-14 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0009_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='Iva',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='Sub_total',
        ),
    ]
