# Generated by Django 4.0.5 on 2022-06-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0010_remove_orden_iva_remove_orden_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount_toppings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
