# Generated by Django 4.0.5 on 2022-06-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0011_product_amount_toppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_sale',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item_sale',
            name='details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
